name: schedulify
description: 'Desktop and mobile compatible, offline-first weekly planner (Schedulify).'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # WINDOW & SYSTEM
  window_manager: ^0.3.9
  screen_retriever: ^0.1.9
  tray_manager: ^0.2.4
  launch_at_startup: ^0.2.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.2

  # UTILS
  intl: ^0.19.0
  local_notifier: ^0.1.6
  audioplayers: ^5.2.1

  # UI
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  dropdown_button2: ^2.3.9

  # DATABASE
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.7

flutter_icons:
  android: false
  ios: false
  image_path: 'assets/app_icon.png'
  windows:
    generate: true
    icon_path: 'assets/app_icon.ico'

# MSIX CONFIGURATION
msix:
  display_name: Schedulify
  publisher_display_name: Eren ISCI
  publisher: CN=Eren ISCI
  identity_name: com.erenisci.schedulify
  msix_version: 1.0.0.0
  logo_path: assets/app_icon.png
  start_menu_icon_path: assets/app_icon.png
  tile_background_color: '#1E1E1E'

flutter:
  uses-material-design: true

  # ASSETS
  assets:
    - assets/sounds/
    - assets/app_icon.ico
    - assets/app_icon.png
